"""Track pending model artifact uploads

Revision ID: 1f7c6e7cd1ef
Revises: 4ce4a40bed70
Create Date: 2026-09-08 11:06:37.719397

"""

from typing import Sequence

import sqlalchemy as sa
from alembic import op

# Revision identifiers, used by Alembic.
revision: str = "1f7c6e7cd1ef"
down_revision: str | Sequence[str] | None = "4ce4a40bed70"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "artifact_uploads",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("video_id", sa.Uuid(), nullable=False),
        sa.Column("storage_key", sa.String(length=200), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["video_id"], ["videos.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("storage_key"),
    )
    op.create_index(
        op.f("ix_artifact_uploads_video_id"),
        "artifact_uploads",
        ["video_id"],
        unique=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_artifact_uploads_video_id"), table_name="artifact_uploads")
    op.drop_table("artifact_uploads")
    # ### end Alembic commands ###
